### ISSUE TITLE
Bugg med Wordpress

### ISSUE THREAD

**Issue by svendahlstrand** [limepark/php-modulen#7]
Halli hallå! Jag får inte Wordpress att fungera, det blir fel. Bugg? Snälla fixa!

**Comment by popsork** [comment]
Det har säkert att göra med #3. Jag räknar med att stöd för det kommer till veckan.

**Comment by hampusn** [comment]
Tror det kan vara lite struligt med PDO. Har du testat att modda WordPress och använda traditionella mysql-api:et i stället? Alltså typ [mysql_connect](https://www.php.net/manual/en/function.mysql-connect.php).

**Comment by hampusn** [comment]
Hur går det med den här buggen? Är arbetet påbörjat snart? Jag har ett projekt som ska lanseras till midsommar och det hade varit fint om det här var fixat tills dess.
